# prometheus.yml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node-app"
    static_configs:
      - targets: ["host.docker.internal:32000"]

  - job_name: "kubernetes-cadvisor"
    static_configs:
      - targets: ["host.docker.internal:10250"]
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: "/metrics/cadvisor"
    bearer_token_file: /etc/prometheus/token.txt

  - job_name: "kube-state-metrics"
    static_configs:
      - targets: ["kube-state-metrics.kube-system.svc.cluster.local:8080"]

  - job_name: "local-app"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]  # Replace with your Node Exporter pod IP