FROM python:3.9-slim

WORKDIR /app

# Install necessary system dependencies
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# Copy requirements file separately for better caching
COPY requirements.txt .

# Install dependencies with no cache to reduce image size
RUN pip install --timeout=900 --no-cache-dir -r requirements.txt

# Copy application files
COPY app/ ./app/

# Copy model files correctly
COPY output/ ./output/

# Set Flask environment variables
ENV FLASK_APP=app/predict.py
ENV FLASK_DEBUG=0

# Expose port 6000
EXPOSE 6000

# Run Flask server
CMD ["flask", "run", "--host=0.0.0.0", "--port=6000"]
